<?php
/**
 * Excerpts and taxonomy helpers.
 */

function kihiro_excerpt_more($more) {
    return ' ... ';
}
add_filter('excerpt_more', 'kihiro_excerpt_more');

function kihiro_excerpt_length($length) {
    return 190;
}
add_filter('excerpt_length', 'kihiro_excerpt_length', 999);

/**
 * Prevent Easy Table of Contents from mistaking a literal selector example
 * for an already-rendered table of contents.
 *
 * Easy Table of Contents checks the entire content for the plain string
 * `ez-toc-container`. Posts that discuss the plugin can therefore lose their
 * automatically inserted TOC. Mask the literal before the plugin's priority
 * 100 content filter, then restore it immediately afterwards.
 */
function kihiro_mask_ez_toc_container_literal($content) {
    if (!is_singular('post') || false === strpos($content, 'ez-toc-container')) {
        return $content;
    }

    // Preserve a real TOC generated by a shortcode or another integration.
    if (preg_match('/<[^>]+\bid=(["\'])ez-toc-container\1/i', $content)) {
        return $content;
    }

    return str_replace(
        'ez-toc-container',
        'ez-toc-kihiro-literal-container',
        $content
    );
}
add_filter('the_content', 'kihiro_mask_ez_toc_container_literal', 99);

function kihiro_restore_ez_toc_container_literal($content) {
    return str_replace(
        'ez-toc-kihiro-literal-container',
        'ez-toc-container',
        $content
    );
}
add_filter('the_content', 'kihiro_restore_ez_toc_container_literal', 101);

function kihiro_custom_excerpt($length = 170) {
    $post = get_post();

    if (!$post instanceof WP_Post) {
        return '';
    }

    $content = wp_strip_all_tags($post->post_excerpt);

    if ('' === $content) {
        $content = strip_shortcodes($post->post_content);
        $content = html_entity_decode(wp_strip_all_tags($content), ENT_QUOTES, 'UTF-8');
    }

    if (mb_strlen($content, 'UTF-8') > $length) {
        return mb_substr($content, 0, $length, 'UTF-8') . '...';
    }

    return $content;
}

function custom_excerpt_pc($length = 170) {
    return kihiro_custom_excerpt($length);
}

function custom_excerpt_sp($length = 100) {
    return kihiro_custom_excerpt($length);
}

function my_tags_in_cat($cat_id) {
    $post_ids = get_objects_in_term((int) $cat_id, 'category');

    if (is_wp_error($post_ids) || empty($post_ids)) {
        return array();
    }

    return wp_get_object_terms($post_ids, 'post_tag');
}

function kihiro_tag_index_visibility_meta_key() {
    return '_kihiro_show_in_tag_index';
}

function kihiro_normalize_tag_index_name($name) {
    $normalized_name = html_entity_decode((string) $name, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $normalized_name = preg_replace('/\x{3000}/u', ' ', $normalized_name);
    $normalized_name = str_replace('＞', '>', $normalized_name);

    return trim(preg_replace('/\s+/u', ' ', $normalized_name));
}

function kihiro_tag_index_name_parts($name) {
    $parts = preg_split('/\s*>\s*/u', kihiro_normalize_tag_index_name($name), -1, PREG_SPLIT_NO_EMPTY);

    return $parts ? $parts : array();
}

function kihiro_is_tag_selected_for_index($tag) {
    if (!$tag instanceof WP_Term) {
        return false;
    }

    return '1' === get_term_meta($tag->term_id, kihiro_tag_index_visibility_meta_key(), true);
}

function kihiro_get_selected_tag_index_tags() {
    $tags = get_tags(
        array(
            'hide_empty' => false,
            'orderby'    => 'name',
            'order'      => 'ASC',
        )
    );

    if (is_wp_error($tags)) {
        return array();
    }

    return array_values(array_filter($tags, 'kihiro_is_tag_selected_for_index'));
}

function kihiro_home_posts_per_page() {
    return -1;
}

function kihiro_get_logbook_total_posts() {
    $counts = wp_count_posts('post');
    $total = isset($counts->publish) ? (int) $counts->publish : 0;
    $excluded_ids = kihiro_excluded_post_ids();

    if ($excluded_ids) {
        $excluded_posts = get_posts(
            array(
                'post_type'              => 'post',
                'post_status'            => 'publish',
                'post__in'               => $excluded_ids,
                'posts_per_page'         => count($excluded_ids),
                'fields'                 => 'ids',
                'no_found_rows'          => true,
                'update_post_meta_cache' => false,
                'update_post_term_cache' => false,
            )
        );
        $total -= count($excluded_posts);
    }

    return max(0, $total);
}

function kihiro_get_logbook_first_post_year() {
    global $wpdb;

    $year = $wpdb->get_var(
        "SELECT MIN(YEAR(post_date))
        FROM {$wpdb->posts}
        WHERE post_type = 'post' AND post_status = 'publish'"
    );

    if (!$year) {
        return '';
    }

    $year = (int) $year;

    return $year >= 1990 ? (string) $year : '';
}

function kihiro_get_logbook_activity_counts($days = 182) {
    $days = max(1, min(366, (int) $days));
    $cache_key = 'kihiro_logbook_activity_' . $days;
    $activity = get_transient($cache_key);

    if (false !== $activity && is_array($activity)) {
        return $activity;
    }

    global $wpdb;

    $since = gmdate('Y-m-d H:i:s', strtotime('-' . ($days - 1) . ' days'));
    $rows = $wpdb->get_results(
        $wpdb->prepare(
            "SELECT DATE(post_date) AS post_day, COUNT(ID) AS post_count
            FROM {$wpdb->posts}
            WHERE post_type = 'post'
                AND post_status = 'publish'
                AND post_date >= %s
            GROUP BY DATE(post_date)",
            $since
        )
    );

    $counts_by_day = array();
    foreach ($rows as $row) {
        $counts_by_day[$row->post_day] = (int) $row->post_count;
    }

    $activity = array();
    for ($offset = $days - 1; $offset >= 0; $offset--) {
        $day = gmdate('Y-m-d', strtotime('-' . $offset . ' days'));
        $activity[] = array(
            'date'  => $day,
            'count' => isset($counts_by_day[$day]) ? $counts_by_day[$day] : 0,
        );
    }

    set_transient($cache_key, $activity, 12 * HOUR_IN_SECONDS);

    return $activity;
}

function kihiro_add_tag_index_visibility_field($taxonomy = '') {
    wp_nonce_field('kihiro_save_tag_index_visibility', 'kihiro_tag_index_visibility_nonce');
    ?>
    <div class="form-field term-kihiro-show-in-tag-index-wrap">
        <label for="kihiro_show_in_tag_index">
            <input type="checkbox" id="kihiro_show_in_tag_index" name="kihiro_show_in_tag_index" value="1">
            タグ一覧に表示する
        </label>
        <p>現実の課題へ戻る入口として、前面に出したいタグだけを選びます。</p>
    </div>
    <?php
}
add_action('post_tag_add_form_fields', 'kihiro_add_tag_index_visibility_field');

function kihiro_edit_tag_index_visibility_field($term) {
    $is_selected = kihiro_is_tag_selected_for_index($term);
    ?>
    <tr class="form-field term-kihiro-show-in-tag-index-wrap">
        <th scope="row"><label for="kihiro_show_in_tag_index">タグ一覧</label></th>
        <td>
            <?php wp_nonce_field('kihiro_save_tag_index_visibility', 'kihiro_tag_index_visibility_nonce'); ?>
            <label>
                <input type="checkbox" id="kihiro_show_in_tag_index" name="kihiro_show_in_tag_index" value="1" <?php checked($is_selected); ?>>
                タグ一覧に表示する
            </label>
            <p class="description">現実の課題へ戻る入口として、前面に出したいタグだけを選びます。</p>
        </td>
    </tr>
    <?php
}
add_action('post_tag_edit_form_fields', 'kihiro_edit_tag_index_visibility_field');

function kihiro_save_tag_index_visibility($term_id) {
    if (!current_user_can('manage_categories')) {
        return;
    }

    $nonce = isset($_POST['kihiro_tag_index_visibility_nonce'])
        ? sanitize_text_field(wp_unslash($_POST['kihiro_tag_index_visibility_nonce']))
        : '';

    if (!wp_verify_nonce($nonce, 'kihiro_save_tag_index_visibility')) {
        return;
    }

    $is_selected = isset($_POST['kihiro_show_in_tag_index']) ? '1' : '0';
    update_term_meta((int) $term_id, kihiro_tag_index_visibility_meta_key(), $is_selected);
}
add_action('created_post_tag', 'kihiro_save_tag_index_visibility');
add_action('edited_post_tag', 'kihiro_save_tag_index_visibility');

function kihiro_tag_index_paths() {
    return array('tags', 'tag-list', 'tag-hierarchy');
}

function kihiro_tag_index_url() {
    return home_url('/tags/');
}

function kihiro_current_request_path() {
    $request_uri = isset($_SERVER['REQUEST_URI'])
        ? wp_unslash($_SERVER['REQUEST_URI'])
        : '';
    $request_path = wp_parse_url($request_uri, PHP_URL_PATH);

    if (!is_string($request_path)) {
        return '';
    }

    $home_path = wp_parse_url(home_url('/'), PHP_URL_PATH);

    if (is_string($home_path) && '/' !== $home_path) {
        $home_path = untrailingslashit($home_path);

        if (0 === strpos($request_path, $home_path . '/')) {
            $request_path = substr($request_path, strlen($home_path));
        }
    }

    return trim($request_path, '/');
}

function kihiro_is_tag_index_request() {
    return in_array(kihiro_current_request_path(), kihiro_tag_index_paths(), true);
}

function kihiro_prepare_tag_index_query($wp_query) {
    $wp_query->is_404       = false;
    $wp_query->is_single    = false;
    $wp_query->is_page      = false;
    $wp_query->is_attachment = false;
    $wp_query->is_singular  = false;
    $wp_query->is_archive   = false;
    $wp_query->is_home      = false;
    $wp_query->is_search    = false;
}

function kihiro_prevent_tag_index_404($preempt, $wp_query) {
    if (!kihiro_is_tag_index_request() || !empty($wp_query->posts)) {
        return $preempt;
    }

    kihiro_prepare_tag_index_query($wp_query);

    return true;
}
add_filter('pre_handle_404', 'kihiro_prevent_tag_index_404', 10, 2);

function kihiro_load_tag_index_template($template) {
    global $wp_query;

    if (!kihiro_is_tag_index_request() || is_page() || !empty($wp_query->posts)) {
        return $template;
    }

    $tag_index_template = locate_template('page-tag-hierarchy.php');

    if (!$tag_index_template) {
        return $template;
    }

    kihiro_prepare_tag_index_query($wp_query);
    status_header(200);

    return $tag_index_template;
}
add_filter('template_include', 'kihiro_load_tag_index_template');

function kihiro_add_tag_index_body_class($classes) {
    if (kihiro_is_tag_index_request()) {
        $classes[] = 'page-template-page-tag-hierarchy';
        $classes[] = 'tag-index';
    }

    return $classes;
}
add_filter('body_class', 'kihiro_add_tag_index_body_class');

function kihiro_filter_tag_index_document_title($title) {
    if (kihiro_is_tag_index_request()) {
        $title['title'] = 'タグ一覧';
    }

    return $title;
}
add_filter('document_title_parts', 'kihiro_filter_tag_index_document_title');

/**
 * Three editorial streams used by the refreshed navigation.
 *
 * Existing tags are used as the source of truth so the theme does not rewrite
 * more than 1,500 posts in the database. Every post belongs to exactly one
 * stream: curation first, technology second, and philosophy as the fallback.
 */
function kihiro_topic_definitions() {
    return array(
        'technology' => array(
            'label'       => '技術ブログ',
            'description' => 'Web制作、プログラミング、デザインの実践記録。',
            'tag_names'   => array(
                'プログラミング', 'Python', 'Git', 'TypeScript', 'JavaScript',
                'React', 'Vue.js', 'WordPress', 'HTML / CSS', 'AI活用',
                'アプリ開発', 'デザイン', 'アルゴリズム', 'ネットワーク',
            ),
        ),
        'philosophy' => array(
            'label'       => '人生哲学',
            'description' => '働き方、生き方、自分との向き合い方について。',
            'tag_names'   => array(),
        ),
        'curation' => array(
            'label'       => '情報のセレクトショップ',
            'description' => '旅、文化、道具、日々の発見から選んだ情報。',
            'tag_names'   => array('情報のセレクトショップ'),
        ),
    );
}

function kihiro_current_topic() {
    $topic = sanitize_key((string) get_query_var('topic'));

    return isset(kihiro_topic_definitions()[$topic]) ? $topic : '';
}

function kihiro_topic_url($topic) {
    if (!isset(kihiro_topic_definitions()[$topic])) {
        return home_url('/');
    }

    return add_query_arg('topic', $topic, home_url('/'));
}

function kihiro_thought_trail_url() {
    return add_query_arg('trail', 'thoughts', home_url('/'));
}

function kihiro_is_thought_trail() {
    return 'thoughts' === sanitize_key((string) get_query_var('trail'));
}

function kihiro_navigation_sections() {
    return array(
        array(
            'title' => '関連サイト',
            'items' => array(
                array(
                    'label'       => 'My portfolio',
                    'url'         => "https://freelance-blog.onrender.com/",
                    'description' => 'フリーランスWEBエンジニアとしてのサイトです。',
                ),
                array(
                    'label'       => 'GitHub',
                    'url'         => "https://github.com/ki-hi-ro",
                    'description' => '私のリポジトリとコミット履歴を確認できます。',
                ),                
                array(
                    'label'       => 'Hatena Blog',
                    'url'         => "https://khirok.hatenadiary.jp/",
                    'description' => 'フリーランスWEB制作の駆け出し期に書いていたブログです。',
                ),  
            ),
        ),        
    );
}

function kihiro_register_topic_query_var($query_vars) {
    $query_vars[] = 'topic';
    $query_vars[] = 'trail';

    return $query_vars;
}
add_filter('query_vars', 'kihiro_register_topic_query_var');

function kihiro_topic_tag_ids() {
    static $topic_tag_ids = null;

    if (null !== $topic_tag_ids) {
        return $topic_tag_ids;
    }

    $topic_tag_ids = array(
        'technology' => array(),
        'curation'   => array(),
    );
    $terms = get_terms(
        array(
            'taxonomy'   => 'post_tag',
            'hide_empty' => false,
        )
    );

    if (is_wp_error($terms)) {
        return $topic_tag_ids;
    }

    $definitions = kihiro_topic_definitions();

    foreach ($terms as $term) {
        foreach (array('technology', 'curation') as $topic) {
            if (in_array($term->name, $definitions[$topic]['tag_names'], true)) {
                $topic_tag_ids[$topic][] = (int) $term->term_id;
            }
        }
    }

    return $topic_tag_ids;
}

function kihiro_apply_topic_query($query, $topic) {
    $tag_ids   = kihiro_topic_tag_ids();
    $tax_query = array('relation' => 'AND');

    if ('curation' === $topic) {
        $tax_query[] = array(
            'taxonomy' => 'post_tag',
            'field'    => 'term_id',
            'terms'    => $tag_ids['curation'],
        );
    } elseif ('technology' === $topic) {
        $tax_query[] = array(
            'taxonomy' => 'post_tag',
            'field'    => 'term_id',
            'terms'    => $tag_ids['technology'],
        );
        if ($tag_ids['curation']) {
            $tax_query[] = array(
                'taxonomy' => 'post_tag',
                'field'    => 'term_id',
                'terms'    => $tag_ids['curation'],
                'operator' => 'NOT IN',
            );
        }
    } else {
        $excluded_tag_ids = array_merge($tag_ids['curation'], $tag_ids['technology']);
        if ($excluded_tag_ids) {
            $tax_query[] = array(
                'taxonomy' => 'post_tag',
                'field'    => 'term_id',
                'terms'    => $excluded_tag_ids,
                'operator' => 'NOT IN',
            );
        } else {
            // With no classification tags, every post belongs to philosophy.
            return;
        }
    }

    $query->set('tax_query', $tax_query);
}

function kihiro_configure_main_query($query) {
    if (is_admin() || !$query->is_main_query()) {
        return;
    }

    if ($query->is_home()) {
        $query->set('posts_per_page', kihiro_home_posts_per_page());
        $query->set('orderby', 'date');
        $query->set('order', 'DESC');

        $topic = kihiro_current_topic();
        if ($topic) {
            kihiro_apply_topic_query($query, $topic);
        }
    } elseif ($query->is_search() || $query->is_tag() || $query->is_date()) {
        $query->set('posts_per_page', 10);
    } else {
        return;
    }

    $excluded_ids = array_unique(
        array_merge(
            (array) $query->get('post__not_in'),
            kihiro_excluded_post_ids()
        )
    );

    $query->set('post__not_in', $excluded_ids);
}
add_action('pre_get_posts', 'kihiro_configure_main_query');

function kihiro_get_archive_months() {
    $archives = get_transient('kihiro_archive_months');

    if (false !== $archives && is_array($archives)) {
        return $archives;
    }

    global $wpdb;

    $rows = $wpdb->get_results(
        "SELECT DISTINCT YEAR(post_date) AS archive_year, MONTH(post_date) AS archive_month
        FROM {$wpdb->posts}
        WHERE post_type = 'post' AND post_status = 'publish'
        ORDER BY post_date DESC"
    );
    $archives = array();

    foreach ($rows as $row) {
        $year = (int) $row->archive_year;
        $archives[$year][] = (int) $row->archive_month;
    }

    set_transient('kihiro_archive_months', $archives, 12 * HOUR_IN_SECONDS);

    return $archives;
}

function kihiro_clear_archive_months_cache() {
    delete_transient('kihiro_archive_months');
    delete_transient('kihiro_logbook_activity_182');
}
add_action('save_post_post', 'kihiro_clear_archive_months_cache');
