<?php
/**
 * Excerpts and taxonomy helpers.
 */

function kihiro_excerpt_more($more) {
    return ' ... ';
}
add_filter('excerpt_more', 'kihiro_excerpt_more');

function kihiro_excerpt_length($length) {
    return 190;
}
add_filter('excerpt_length', 'kihiro_excerpt_length', 999);

/**
 * Prevent Easy Table of Contents from mistaking a literal selector example
 * for an already-rendered table of contents.
 *
 * Easy Table of Contents checks the entire content for the plain string
 * `ez-toc-container`. Posts that discuss the plugin can therefore lose their
 * automatically inserted TOC. Mask the literal before the plugin's priority
 * 100 content filter, then restore it immediately afterwards.
 */
function kihiro_mask_ez_toc_container_literal($content) {
    if (!is_singular('post') || false === strpos($content, 'ez-toc-container')) {
        return $content;
    }

    // Preserve a real TOC generated by a shortcode or another integration.
    if (preg_match('/<[^>]+\bid=(["\'])ez-toc-container\1/i', $content)) {
        return $content;
    }

    return str_replace(
        'ez-toc-container',
        'ez-toc-kihiro-literal-container',
        $content
    );
}
add_filter('the_content', 'kihiro_mask_ez_toc_container_literal', 99);

function kihiro_restore_ez_toc_container_literal($content) {
    return str_replace(
        'ez-toc-kihiro-literal-container',
        'ez-toc-container',
        $content
    );
}
add_filter('the_content', 'kihiro_restore_ez_toc_container_literal', 101);

function kihiro_custom_excerpt($length = 170) {
    $post = get_post();

    if (!$post instanceof WP_Post) {
        return '';
    }

    $content = wp_strip_all_tags($post->post_excerpt);

    if ('' === $content) {
        $content = strip_shortcodes($post->post_content);
        $content = html_entity_decode(wp_strip_all_tags($content), ENT_QUOTES, 'UTF-8');
    }

    if (mb_strlen($content, 'UTF-8') > $length) {
        return mb_substr($content, 0, $length, 'UTF-8') . '...';
    }

    return $content;
}

function custom_excerpt_pc($length = 170) {
    return kihiro_custom_excerpt($length);
}

function custom_excerpt_sp($length = 100) {
    return kihiro_custom_excerpt($length);
}

function my_tags_in_cat($cat_id) {
    $post_ids = get_objects_in_term((int) $cat_id, 'category');

    if (is_wp_error($post_ids) || empty($post_ids)) {
        return array();
    }

    return wp_get_object_terms($post_ids, 'post_tag');
}

/**
 * Three editorial streams used by the refreshed navigation.
 *
 * Existing tags are used as the source of truth so the theme does not rewrite
 * more than 1,500 posts in the database. Every post belongs to exactly one
 * stream: curation first, technology second, and philosophy as the fallback.
 */
function kihiro_topic_definitions() {
    return array(
        'technology' => array(
            'label'       => '技術ブログ',
            'description' => 'Web制作、プログラミング、デザインの実践記録。',
            'tag_names'   => array(
                'プログラミング', 'Python', 'Git', 'TypeScript', 'JavaScript',
                'React', 'Vue.js', 'WordPress', 'HTML / CSS', 'AI活用',
                'アプリ開発', 'デザイン', 'アルゴリズム', 'ネットワーク',
            ),
        ),
        'philosophy' => array(
            'label'       => '人生哲学',
            'description' => '働き方、生き方、自分との向き合い方について。',
            'tag_names'   => array(),
        ),
        'curation' => array(
            'label'       => '情報のセレクトショップ',
            'description' => '旅、文化、道具、日々の発見から選んだ情報。',
            'tag_names'   => array('情報のセレクトショップ'),
        ),
    );
}

function kihiro_current_topic() {
    $topic = sanitize_key((string) get_query_var('topic'));

    return isset(kihiro_topic_definitions()[$topic]) ? $topic : '';
}

function kihiro_topic_url($topic) {
    if (!isset(kihiro_topic_definitions()[$topic])) {
        return home_url('/');
    }

    return add_query_arg('topic', $topic, home_url('/'));
}

function kihiro_thought_trail_url() {
    return add_query_arg('trail', 'thoughts', home_url('/'));
}

function kihiro_is_thought_trail() {
    return 'thoughts' === sanitize_key((string) get_query_var('trail'));
}

function kihiro_navigation_sections() {
    return array(
        array(
            'title' => '読む',
            'items' => array(
                array(
                    'label'       => '写真と言葉',
                    'url'         => home_url('/'),
                    'description' => 'ランダムに現れる写真、名言、最新記事。',
                ),
                array(
                    'label'       => '最新の記事',
                    'url'         => home_url('/#latest-notes'),
                    'description' => 'いま近い場所にある記録から読む。',
                ),
                array(
                    'label'       => '思考の軌跡',
                    'url'         => kihiro_thought_trail_url(),
                    'description' => '過去記事を日付とタイトルだけで俯瞰する。',
                ),
            ),
        ),
        // array(
        //     'title' => 'テーマ',
        //     'items' => array(
        //         array(
        //             'label'       => '人生哲学',
        //             'url'         => kihiro_topic_url('philosophy'),
        //             'description' => '働き方、生き方、自分との向き合い方。',
        //         ),
        //         array(
        //             'label'       => '技術ブログ',
        //             'url'         => kihiro_topic_url('technology'),
        //             'description' => '制作、実装、デザインの実践記録。',
        //         ),
        //         array(
        //             'label'       => '情報のセレクトショップ',
        //             'url'         => kihiro_topic_url('curation'),
        //             'description' => '旅、文化、道具、日々の発見。',
        //         ),
        //     ),
        // ),
        // array(
        //     'title' => '探す',
        //     'items' => array(
        //         array(
        //             'label'       => '検索',
        //             'url'         => home_url('/?s='),
        //             'description' => '言葉から過去の記録へ入る。',
        //         ),
        //         // array(
        //         //     'label'       => '年月アーカイブ',
        //         //     'url'         => home_url('/#archive-map'),
        //         //     'description' => '時間の流れから記事をたどる。',
        //         // ),
        //     ),
        // ),
    );
}

function kihiro_register_topic_query_var($query_vars) {
    $query_vars[] = 'topic';
    $query_vars[] = 'trail';

    return $query_vars;
}
add_filter('query_vars', 'kihiro_register_topic_query_var');

function kihiro_topic_tag_ids() {
    static $topic_tag_ids = null;

    if (null !== $topic_tag_ids) {
        return $topic_tag_ids;
    }

    $topic_tag_ids = array(
        'technology' => array(),
        'curation'   => array(),
    );
    $terms = get_terms(
        array(
            'taxonomy'   => 'post_tag',
            'hide_empty' => false,
        )
    );

    if (is_wp_error($terms)) {
        return $topic_tag_ids;
    }

    $definitions = kihiro_topic_definitions();

    foreach ($terms as $term) {
        foreach (array('technology', 'curation') as $topic) {
            if (in_array($term->name, $definitions[$topic]['tag_names'], true)) {
                $topic_tag_ids[$topic][] = (int) $term->term_id;
            }
        }
    }

    return $topic_tag_ids;
}

function kihiro_apply_topic_query($query, $topic) {
    $tag_ids   = kihiro_topic_tag_ids();
    $tax_query = array('relation' => 'AND');

    if ('curation' === $topic) {
        $tax_query[] = array(
            'taxonomy' => 'post_tag',
            'field'    => 'term_id',
            'terms'    => $tag_ids['curation'],
        );
    } elseif ('technology' === $topic) {
        $tax_query[] = array(
            'taxonomy' => 'post_tag',
            'field'    => 'term_id',
            'terms'    => $tag_ids['technology'],
        );
        if ($tag_ids['curation']) {
            $tax_query[] = array(
                'taxonomy' => 'post_tag',
                'field'    => 'term_id',
                'terms'    => $tag_ids['curation'],
                'operator' => 'NOT IN',
            );
        }
    } else {
        $excluded_tag_ids = array_merge($tag_ids['curation'], $tag_ids['technology']);
        if ($excluded_tag_ids) {
            $tax_query[] = array(
                'taxonomy' => 'post_tag',
                'field'    => 'term_id',
                'terms'    => $excluded_tag_ids,
                'operator' => 'NOT IN',
            );
        } else {
            // With no classification tags, every post belongs to philosophy.
            return;
        }
    }

    $query->set('tax_query', $tax_query);
}

function kihiro_configure_main_query($query) {
    if (is_admin() || !$query->is_main_query()) {
        return;
    }

    if ($query->is_home()) {
        $query->set('posts_per_page', 3);
        $query->set('orderby', 'modified');
        $query->set('order', 'DESC');

        $topic = kihiro_current_topic();
        if ($topic) {
            kihiro_apply_topic_query($query, $topic);
        }
    } elseif ($query->is_search() || $query->is_tag() || $query->is_date()) {
        $query->set('posts_per_page', 10);
    } else {
        return;
    }

    $excluded_ids = array_unique(
        array_merge(
            (array) $query->get('post__not_in'),
            kihiro_excluded_post_ids()
        )
    );

    $query->set('post__not_in', $excluded_ids);
}
add_action('pre_get_posts', 'kihiro_configure_main_query');

function kihiro_get_archive_months() {
    $archives = get_transient('kihiro_archive_months');

    if (false !== $archives && is_array($archives)) {
        return $archives;
    }

    global $wpdb;

    $rows = $wpdb->get_results(
        "SELECT DISTINCT YEAR(post_date) AS archive_year, MONTH(post_date) AS archive_month
        FROM {$wpdb->posts}
        WHERE post_type = 'post' AND post_status = 'publish'
        ORDER BY post_date DESC"
    );
    $archives = array();

    foreach ($rows as $row) {
        $year = (int) $row->archive_year;
        $archives[$year][] = (int) $row->archive_month;
    }

    set_transient('kihiro_archive_months', $archives, 12 * HOUR_IN_SECONDS);

    return $archives;
}

function kihiro_clear_archive_months_cache() {
    delete_transient('kihiro_archive_months');
}
add_action('save_post_post', 'kihiro_clear_archive_months_cache');
