<?php
/**
 * Excerpts, logbook metrics, and archive queries.
 */

function kihiro_excerpt_more($more) {
    return ' ... ';
}
add_filter('excerpt_more', 'kihiro_excerpt_more');

function kihiro_excerpt_length($length) {
    return 190;
}
add_filter('excerpt_length', 'kihiro_excerpt_length', 999);

/**
 * Prevent Easy Table of Contents from mistaking a literal selector example
 * for an already-rendered table of contents.
 *
 * Easy Table of Contents checks the entire content for the plain string
 * `ez-toc-container`. Posts that discuss the plugin can therefore lose their
 * automatically inserted TOC. Mask the literal before the plugin's priority
 * 100 content filter, then restore it immediately afterwards.
 */
function kihiro_mask_ez_toc_container_literal($content) {
    if (!is_singular('post') || false === strpos($content, 'ez-toc-container')) {
        return $content;
    }

    // Preserve a real TOC generated by a shortcode or another integration.
    if (preg_match('/<[^>]+\bid=(["\'])ez-toc-container\1/i', $content)) {
        return $content;
    }

    return str_replace(
        'ez-toc-container',
        'ez-toc-kihiro-literal-container',
        $content
    );
}
add_filter('the_content', 'kihiro_mask_ez_toc_container_literal', 99);

function kihiro_restore_ez_toc_container_literal($content) {
    return str_replace(
        'ez-toc-kihiro-literal-container',
        'ez-toc-container',
        $content
    );
}
add_filter('the_content', 'kihiro_restore_ez_toc_container_literal', 101);

function kihiro_custom_excerpt($length = 170) {
    $post = get_post();

    if (!$post instanceof WP_Post) {
        return '';
    }

    $content = wp_strip_all_tags($post->post_excerpt);

    if ('' === $content) {
        $content = strip_shortcodes($post->post_content);
        $content = html_entity_decode(wp_strip_all_tags($content), ENT_QUOTES, 'UTF-8');
    }

    if (mb_strlen($content, 'UTF-8') > $length) {
        return mb_substr($content, 0, $length, 'UTF-8') . '...';
    }

    return $content;
}

function custom_excerpt_pc($length = 170) {
    return kihiro_custom_excerpt($length);
}

function custom_excerpt_sp($length = 100) {
    return kihiro_custom_excerpt($length);
}

function my_tags_in_cat($cat_id) {
    $post_ids = get_objects_in_term((int) $cat_id, 'category');

    if (is_wp_error($post_ids) || empty($post_ids)) {
        return array();
    }

    return wp_get_object_terms($post_ids, 'post_tag');
}

function kihiro_home_posts_per_page() {
    return -1;
}

function kihiro_get_logbook_total_posts() {
    $counts = wp_count_posts('post');
    $total = isset($counts->publish) ? (int) $counts->publish : 0;
    $excluded_ids = kihiro_excluded_post_ids();

    if ($excluded_ids) {
        $excluded_posts = get_posts(
            array(
                'post_type'              => 'post',
                'post_status'            => 'publish',
                'post__in'               => $excluded_ids,
                'posts_per_page'         => count($excluded_ids),
                'fields'                 => 'ids',
                'no_found_rows'          => true,
                'update_post_meta_cache' => false,
                'update_post_term_cache' => false,
            )
        );
        $total -= count($excluded_posts);
    }

    return max(0, $total);
}

function kihiro_get_logbook_first_post_year() {
    global $wpdb;

    $year = $wpdb->get_var(
        "SELECT MIN(YEAR(post_date))
        FROM {$wpdb->posts}
        WHERE post_type = 'post' AND post_status = 'publish'"
    );

    if (!$year) {
        return '';
    }

    $year = (int) $year;

    return $year >= 1990 ? (string) $year : '';
}

function kihiro_get_logbook_activity_counts($days = 182) {
    $days = max(1, min(366, (int) $days));
    $cache_key = 'kihiro_logbook_activity_' . $days;
    $activity = get_transient($cache_key);

    if (false !== $activity && is_array($activity)) {
        return $activity;
    }

    global $wpdb;

    $since = gmdate('Y-m-d H:i:s', strtotime('-' . ($days - 1) . ' days'));
    $rows = $wpdb->get_results(
        $wpdb->prepare(
            "SELECT DATE(post_date) AS post_day, COUNT(ID) AS post_count
            FROM {$wpdb->posts}
            WHERE post_type = 'post'
                AND post_status = 'publish'
                AND post_date >= %s
            GROUP BY DATE(post_date)",
            $since
        )
    );

    $counts_by_day = array();
    foreach ($rows as $row) {
        $counts_by_day[$row->post_day] = (int) $row->post_count;
    }

    $activity = array();
    for ($offset = $days - 1; $offset >= 0; $offset--) {
        $day = gmdate('Y-m-d', strtotime('-' . $offset . ' days'));
        $activity[] = array(
            'date'  => $day,
            'count' => isset($counts_by_day[$day]) ? $counts_by_day[$day] : 0,
        );
    }

    set_transient($cache_key, $activity, 12 * HOUR_IN_SECONDS);

    return $activity;
}

function kihiro_configure_main_query($query) {
    if (is_admin() || !$query->is_main_query()) {
        return;
    }

    if ($query->is_home()) {
        $query->set('posts_per_page', kihiro_home_posts_per_page());
        $query->set('orderby', 'date');
        $query->set('order', 'DESC');

        $topic = kihiro_current_topic();
        if ($topic) {
            kihiro_apply_topic_query($query, $topic);
        }
    } elseif ($query->is_search() || $query->is_tag() || $query->is_date()) {
        $query->set('posts_per_page', 10);
    } else {
        return;
    }

    $excluded_ids = array_unique(
        array_merge(
            (array) $query->get('post__not_in'),
            kihiro_excluded_post_ids()
        )
    );

    $query->set('post__not_in', $excluded_ids);
}
add_action('pre_get_posts', 'kihiro_configure_main_query');

function kihiro_get_archive_months() {
    $archives = get_transient('kihiro_archive_months');

    if (false !== $archives && is_array($archives)) {
        return $archives;
    }

    global $wpdb;

    $rows = $wpdb->get_results(
        "SELECT DISTINCT YEAR(post_date) AS archive_year, MONTH(post_date) AS archive_month
        FROM {$wpdb->posts}
        WHERE post_type = 'post' AND post_status = 'publish'
        ORDER BY post_date DESC"
    );
    $archives = array();

    foreach ($rows as $row) {
        $year = (int) $row->archive_year;
        $archives[$year][] = (int) $row->archive_month;
    }

    set_transient('kihiro_archive_months', $archives, 12 * HOUR_IN_SECONDS);

    return $archives;
}

function kihiro_clear_archive_months_cache() {
    delete_transient('kihiro_archive_months');
    delete_transient('kihiro_logbook_activity_182');
}
add_action('save_post_post', 'kihiro_clear_archive_months_cache');
